Update RDS Postgres

diff --git a/RDS Postgres b/RDS Postgres
--- a/RDS Postgres
+++ b/RDS Postgres
@@ -1,63 +1,93 @@
-Refer "https://docs.datadoghq.com/database_monitoring/setup_postgres/rds/?tab=postgres15"
+Create a EC2 Instance and setup postgresql RDS in /etc/datadog/conf.d/postgres.d
 
 # Update packages
 sudo yum update -y
 
 # Install PostgreSQL client (version 15 shown; change if needed)
-sudo amazon-linux-extras enable postgresql15
+sudo amazon-linux-extras enable postgresql15 (optional)
 sudo yum install -y postgresql15
 
+1.Configure Database Parameter:
+Refer page "https://docs.datadoghq.com/database_monitoring/setup_postgres/rds/?tab=postgres15" 
 
+2.Login RDS postgresql database from EC2 Instance
 psql -h apmdt.cdiggq2s868n.ap-south-1.rds.amazonaws.com -U postgres -d postgres -p 5432
-psql -d postgres -c "select version();"
 
-exit
-export PGHOST="apmdt.cdiggq2s868n.ap-south-1.rds.amazonaws.com"
-export PGPORT=5432
-export PGUSER="postgres"          # or your master/privileged user
-export PGPASSWORD="YOUR_PASSWORD"
-psql -d postgres -c "select version();"
-psql -d postgres -c "CREATE DATABASE demo_db;"
+Create a datadog user
+CREATE USER datadog WITH password '<PASSWORD>';
 
-psql -v ON_ERROR_STOP=1 -d demo_db <<'SQL'
-CREATE TABLE IF NOT EXISTS users (
-  id          bigserial PRIMARY KEY,
-  email       text UNIQUE NOT NULL,
-  full_name   text NOT NULL,
-  created_at  timestamptz NOT NULL DEFAULT now()
-);
+3.Give the datadog user permission to relevant tables
 
-INSERT INTO users (email, full_name) VALUES
-('alice@example.com','Alice A.'),
-('bob@example.com','Bob B.'),
-('carol@example.com','Carol C.')
-ON CONFLICT (email) DO NOTHING;
+ALTER ROLE datadog INHERIT;
 
-\q
-SQL
+Create the following schema in every database:
+CREATE SCHEMA datadog;
+GRANT USAGE ON SCHEMA datadog TO datadog;
+GRANT USAGE ON SCHEMA public TO datadog;
+GRANT pg_monitor TO datadog;
+CREATE EXTENSION IF NOT EXISTS pg_stat_statements schema public;
 
-cat > /tmp/users.csv <<'CSV'
-email,full_name,created_at
-alice@example.com,Alice A.,2023-01-01T10:00:00Z
-bob@example.com,Bob B.,2023-01-02T11:00:00Z
-carol@example.com,Carol C.,2023-01-03T12:00:00Z
-CSV
+Create the following function in every database to enable the Agent to collect explain plans:
+---------------------------------------------------------------------------------------------
+CREATE OR REPLACE FUNCTION datadog.explain_statement(
+   l_query TEXT,
+   OUT explain JSON
+)
+RETURNS SETOF JSON AS
+$$
+DECLARE
+curs REFCURSOR;
+plan JSON;
 
-psql -d demo_db -c "\copy users(email,full_name,created_at) FROM '/tmp/users.csv' WITH (FORMAT csv, HEADER true)"
-postgres=> SELECT * FROM users;
+BEGIN
+   SET TRANSACTION READ ONLY;
 
+   OPEN curs FOR EXECUTE pg_catalog.concat('EXPLAIN (FORMAT JSON) ', l_query);
+   FETCH curs INTO plan;
+   CLOSE curs;
+   RETURN QUERY SELECT plan;
+END;
+$$
+LANGUAGE 'plpgsql'
+RETURNS NULL ON NULL INPUT
+SECURITY DEFINER;
 
-1.Bulk Insert Many Row
-INSERT INTO users (email, full_name)
-SELECT 
-  'user' || i || '@example.com',
-  'User ' || i
-FROM generate_series(1, 10000) AS s(i);
+4.Verify database permissions (replace localhost to your RDS database endpoing)
 
-2.Run heavy read queries
-SELECT * FROM users ORDER BY created_at DESC LIMIT 100;
+psql -h localhost -U datadog postgres -A \
+  -c "select * from pg_stat_database limit 1;" \
+  && echo -e "\e[0;32mPostgres connection - OK\e[0m" \
+  || echo -e "\e[0;31mCannot connect to Postgres\e[0m"
+psql -h localhost -U datadog postgres -A \
+  -c "select * from pg_stat_activity limit 1;" \
+  && echo -e "\e[0;32mPostgres pg_stat_activity read OK\e[0m" \
+  || echo -e "\e[0;31mCannot read from pg_stat_activity\e[0m"
+psql -h localhost -U datadog postgres -A \
+  -c "select * from pg_stat_statements limit 1;" \
+  && echo -e "\e[0;32mPostgres pg_stat_statements read OK\e[0m" \
+  || echo -e "\e[0;31mCannot read from pg_stat_statements\e[0m"
 
-3.Update Many Rows
-UPDATE users 
-SET full_name = full_name || ' [updated]' 
-WHERE id % 100 = 0;
+5.Install and configure the agent on EC2 Instance
+Edit the postgres.d/conf.yaml file to point to your host / port and set the masters to monitor
+
+init_config:
+instances:
+  - dbm: true
+    host: '<AWS_INSTANCE_ENDPOINT>'
+    port: 5432
+    username: datadog
+    password: 'ENC[datadog_user_database_password]'
+    aws:
+      instance_endpoint: '<AWS_INSTANCE_ENDPOINT>'
+      region: '<REGION>'
+    tags:
+      - "dbinstanceidentifier:<DB_INSTANCE_NAME>"
+
+    ## Required for Postgres 9.6: Uncomment these lines to use the functions created in the setup
+    # pg_stat_statements_view: datadog.pg_stat_statements()
+    # pg_stat_activity_view: datadog.pg_stat_activity()
+
+    ## Optional: Connect to a different database if needed for `custom_queries`
+    # dbname: '<DB_NAME>'
+
+6.Restart the agent
